{
  pkgs,
  lib,
  inputs,
  ...
}:
{

  home.packages = with pkgs; [
    wlogout
    rofi-wayland
    rofi-bluetooth
    inputs.hyprland-plugins.packages.${pkgs.system}.grimblast
    inputs.ags.packages.${pkgs.system}.ags
    inputs.hyprshot.packages.${pkgs.syste}.hyprshot
    brightnessctl
    killall
    inotify-tools
    libsForQt5.qt5.qtwayland
    qt6.qtwayland
    hyprpicker
    cliphist
    nwg-displays
    wlr-randr
    hyprlock
    notify-desktop
    blueman
    networkmanagerapplet
    nm-tray
    xfce.thunar
    hypridle
  ];
}
